name: DigitalPersona Access Management API
shortName: DPAM
repo: digitalpersona-access-management-api
git: 'https://github.com/hidglobal'
npm: 'https://www.npmjs.com/package'
digitalPersonaUrl: 'https://www.hidglobal.com/products/software/digitalpersona/digitalpersona'
liteClientUrl: 'https://crossmatch.hid.gl/lite-client'
